services:
  - type: web
    name: futebol-value
    env: docker
    plan: free
    autoDeploy: true

    dockerfilePath: ./Dockerfile

    envVars:
      - key: FOOTBALL_API_KEY
        sync: false
      - key: EXTERNAL_ODDS_KEY
        sync: false
      - key: ENVIRONMENT
        value: "production"
