services:
  - type: web
    name: futebol-ai
    env: docker
    repo: https://github.com/SEU_USUARIO/SEU_REPOSITORIO
    plan: free
    autoDeploy: true

    # Render vai usar o Dockerfile automaticamente
    dockerfilePath: ./Dockerfile

    envVars:
      - key: PORT
        value: 8000

      - key: FOOTBALL_API_KEY
        sync: false    # inserir manualmente no dashboard

      - key: EXTERNAL_ODDS_KEY
        sync: false

      - key: ENVIRONMENT
        value: "production"
